### ISSUE TITLE
Allow to set no size cap

### ISSUE THREAD

**Issue by torkleyy** [rustgd/shrev-rs#13]
Would be helpful to have that in Specs since accuracy is important for the metadata.

**Comment by torkleyy** [comment]
cc @Aceeri

**Comment by Aceeri** [comment]
This will probably require a more specialized ring buffer, since resizing isn't as simple as just resizing the Vec (well in a theoretical infinite memory sense it is, but we don't want to chew up all memory).

**Comment by torkleyy** [comment]
Yeah I know. Another thing is that sometimes you write single events, sometimes only the whole buffer at once. The latter one would be easier to work with here.

**Comment by Rhuagh** [comment]
This was resolved in the last PR.
